---
- name: Start backend server
  shell: |
    cd /home/ubuntu/application/backend/
    npm install
    npm run build
    pm2 start ./dist/main.js
  register: output

- debug:
    var: output.stdout_lines