---
- name: add content to .env file
  shell: |
    cd /home/ubuntu/application/backend/
    echo "ENVIRONMENT=production" > .env
    echo "NODE_ENV=production" >> .env
    echo "TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> .env
    echo "TYPEORM_ENTITIES=\"./src/modules/domain/**/*.entity.ts\"" >> .env
    echo "TYPEORM_HOST=$TYPEORM_HOST" >> .env
    echo "TYPEORM_PORT=$TYPEORM_PORT" >> .env
    echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> .env
    echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> .env
    echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> .env

- name: Start backend server
  shell: |
    cd /home/ubuntu/application/backend/
    npm install
    npm run build
    pm2 start dist/main.js
  register: output

- debug:
    var: output.stdout_lines